export enum IngredientsActionTypes {
    INGREDIENT_DAILY_LIST = '@@ingredients/INGREDIENTS_DAILY_LIST',
    INGREDIENT_DAILY_LIST_SUCCESS = '@@ingredients/INGREDIENTS_DAILY_LIST_SUCCESS',
    INGREDIENT_DAILY_LIST_ERROR = '@@ingredients/INGREDIENTS_DAILY_LIST_ERROR',
}
