export enum ReportActionTypes {
    DASHBOARD_EARNING_REPORT = '@@report/DASHBOARD_EARNING_REPORT',
    DASHBOARD_EARNING_REPORT_SUCCESS = '@@report/DASHBOARD_EARNING_REPORT_SUCCESS',
    DASHBOARD_EARNING_REPORT_ERROR = '@@report/DASHBOARD_EARNING_REPORT_ERROR',

    DASHBOARD_SALES_REPORT = '@@report/DASHBOARD_SALES_REPORT',
    DASHBOARD_SALES_REPORT_SUCCESS = '@@report/DASHBOARD_SALES_REPORT_SUCCESS',
    DASHBOARD_SALES_REPORT_ERROR = '@@report/DASHBOARD_SALES_REPORT_ERROR',

    ORDER_REPORT_LIST = '@@report/ORDER_REPORT_LIST',
    ORDER_REPORT_LIST_SUCCESS = '@@report/ORDER_REPORT_LIST_SUCCESS',
    ORDER_REPORT_LIST_ERROR = '@@report/ORDER_REPORT_LIST_ERROR',

    INGREDIENT_REPORT_LIST = '@@report/INGREDIENT_REPORT_LIST',
    INGREDIENT_REPORT_LIST_SUCCESS = '@@report/INGREDIENT_REPORT_LIST_SUCCESS',
    INGREDIENT_REPORT_LIST_ERROR = '@@report/INGREDIENT_REPORT_LIST_ERROR',
}
