export enum TerminalActionTypes {
    TERMINAL_LIST = '@@terminal/TERMINAL_LIST',
    TERMINAL_LIST_SUCCESS = '@@terminal/TERMINAL_LIST_SUCCESS',
    TERMINAL_LIST_ERROR = '@@terminal/TERMINAL_LIST_ERROR',

    TERMINAL_CREATE = '@@terminal/TERMINAL_CREATE',
    TERMINAL_CREATE_SUCCESS = '@@terminal/TERMINAL_CREATE_SUCCESS',
    TERMINAL_CREATE_ERROR = '@@terminal/TERMINAL_CREATE_ERROR',

    TERMINAL_UPDATE = '@@terminal/TERMINAL_UPDATE',
    TERMINAL_UPDATE_SUCCESS = '@@terminal/TERMINAL_UPDATE_SUCCESS',
    TERMINAL_UPDATE_ERROR = '@@terminal/TERMINAL_UPDATE_ERROR',

    TERMINAL_DELETE = '@@terminal/TERMINAL_DELETE',
    TERMINAL_DELETE_SUCCESS = '@@terminal/TERMINAL_DELETE_SUCCESS',
    TERMINAL_DELETE_ERROR = '@@terminal/TERMINAL_DELETE_ERROR',
}
