export enum MenuManagementCategoryActionTypes {
    CATEGORY_UPDATE_DISABLE = '@@menu/CATEGORY_UPDATE_DISABLE',
    CATEGORY_UPDATE_DISABLE_SUCCESS = '@@menu/CATEGORY_UPDATE_DISABLE_SUCCESS',
    CATEGORY_UPDATE_DISABLE_ERROR = '@@menu/CATEGORY_UPDATE_DISABLE_ERROR',

    REGISTER_CATEGORY = '@@menu/REGISTER_CATEGORY',
    REGISTER_CATEGORY_SUCCESS = '@@menu/REGISTER_CATEGORY_SUCCESS',
    REGISTER_CATEGORY_ERROR = '@@menu/REGISTER_CATEGORY_ERROR',

    DELETE_CATEGORY = '@@menu/DELETE_CATEGORY',
    DELETE_CATEGORY_SUCCESS = '@@menu/DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_ERROR = '@@menu/DELETE_CATEGORY_ERROR',

    UPDATE_CATEGORY = '@@menu/UPDATE_CATEGORY',
    UPDATE_CATEGORY_SUCCESS = '@@menu/UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_ERROR = '@@menu/UPDATE_CATEGORY_ERROR',

    CATEGORY_UPDATE_ISACTIVE = '@@menu/CATEGORY_UPDATE_ISACTIVE',
    CATEGORY_UPDATE_ISACTIVE_SUCCESS = '@@menu/CATEGORY_UPDATE_ISACTIVE_SUCCESS',
    CATEGORY_UPDATE_ISACTIVE_ERROR = '@@menu/CATEGORY_UPDATE_ISACTIVE_ERROR',

    CATEGORY_OUTLET_LISTS = '@@menu/CATEGORY_OUTLET_LISTS',
    CATEGORY_OUTLET_LISTS_SUCCESS = '@@menu/CATEGORY_OUTLET_LISTS_SUCCESS',
    CATEGORY_OUTLET_LISTS_ERROR = '@@menu/CATEGORY_OUTLET_LISTS_ERROR',

    CATEGORY_ITEM_LIST = '@@menu/CATEGORY_ITEM_LIST',
    CATEGORY_ITEM_LIST_SUCCESS = '@@menu/CATEGORY_ITEM_LIST_SUCCESS',
    CATEGORY_ITEM_LIST_ERROR = '@@menu/CATEGORY_ITEM_LIST_ERROR',
}
