export enum TableMappingActionTypes {
    AREA_CREATE = '@@table/AREA_CREATE',
    AREA_CREATE_SUCCESS = '@@table/AREA_CREATE_SUCCESS',
    AREA_CREATE_ERROR = '@@table/AREA_CREATE_ERROR',

    AREA_DELETE = '@@table/AREA_DELETE',
    AREA_DELETE_SUCCESS = '@@table/AREA_DELETE_SUCCESS',
    AREA_DELETE_ERROR = '@@table/AREA_DELETE_ERROR',

    AREA_UPDATE = '@@table/AREA_UPDATE',
    AREA_UPDATE_SUCCESS = '@@table/AREA_UPDATE_SUCCESS',
    AREA_UPDATE_ERROR = '@@table/AREA_UPDATE_ERROR',

    AREA_TABLES = '@@table/AREA_TABLES',
    AREA_TABLES_SUCCESS = '@@table/AREA_TABLES_SUCCESS',
    AREA_TABLES_ERROR = '@@table/AREA_TABLES_ERROR',

    AREA_ADD = '@@table/AREA_ADD',
    AREA_ADD_SUCCESS = '@@table/AREA_ADD_SUCCESS',
    AREA_ADD_ERROR = '@@table/AREA_ADD_ERROR',
}
