export enum StaffActionTypes {
    STAFF_LIST = '@@staff/STAFF_LIST',
    STAFF_LIST_SUCCESS = '@@staff/STAFF_LIST_SUCCESS',
    STAFF_LIST_ERROR = '@@staff/STAFF_LIST_ERROR',

    STAFF_UPDATE = '@@staff/STAFF_UPDATE',
    STAFF_UPDATE_SUCCESS = '@@staff/STAFF_LIST_SUCCESS',
    STAFF_UPDATE_ERROR = '@@staff/STAFF_UPDATE_ERROR',

    STAFF_DELETE = '@@staff/STAFF_DELETE',
    STAFF_DELETE_SUCCESS = '@@staff/STAFF_DELETE_SUCCESS',
    STAFF_DELETE_ERROR = '@@staff/STAFF_DELETE_ERROR',

    STAFF_CREATE = '@@staff/STAFF_CREATE',
    STAFF_CREATE_SUCCESS = '@@staff/STAFF_CREATE_SUCCESS',
    STAFF_CREATE_ERROR = '@@staff/STAFF_CREATE_ERROR',

    STAFF_DETAILS = '@@staff/STAFF_DETAILS',
    STAFF_DETAILS_SUCCESS = '@@staff/STAFF_DETAILS_SUCCESS',
    STAFF_DETAILS_ERROR = '@@staff/STAFF_DETAILS_ERROR',

    STAFF_ALLOCATION_UPDATE = '@@staff/STAFF_ALLOCATION_UPDATE',
    STAFF_ALLOCATION_UPDATE_SUCCESS = '@@staff/STAFF_ALLOCATION_UPDATE_SUCCESS',
    STAFF_ALLOCATION_UPDATE_ERROR = '@@staff/STAFF_ALLOCATION_UPDATE_ERROR',

    STAFF_ATTENDANCE_UPDATE = '@@staff/STAFF_ATTENDANCE_UPDATE',
    STAFF_ATTENDANCE_UPDATE_SUCCESS = '@@staff/STAFF_ATTENDANCE_UPDATE_SUCCESS',
    STAFF_ATTENDANCE_UPDATE_ERROR = '@@staff/STAFF_ATTENDANCE_UPDATE_ERROR',
}
